### ISSUE TITLE
Dirs are not created in container

### ISSUE THREAD

**Issue by mikunn** [7ojo/perl6-platform#30]
I have this in `project.yml` file:

```
dirs:
  /var/www/portal/Data/federation:
    owner: www-data
    group: www-data
    mode: 775
```

The generated command is as follows:
```
docker exec portal bash -c mkdir -p /var/www/portal/Data/federation ; chown www-data:www-data
```
It's missing '-charaters around mkdir and friends, so the the command should be
```
docker exec portal bash -c 'mkdir -p /var/www/portal/Data/federation ; chown www-data:www-data'
```
